services:
  db:
    image: postgres:latest
    container_name: mental-health-db
    environment:
      POSTGRES_PASSWORD: MentalHealth123
      POSTGRES_USER: MentalHealth
      POSTGRES_DB: MentalHealth
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
volumes:
  pg_data:
